### ISSUE TITLE
Is it possible to allow usual messages in a Telegram group during the game?

### ISSUE THREAD

**Issue by DoopityWha** [sasha00123/ai-dungeon-bot#1]
I was able to chat normally while the bot was active - now it detects every unprocessed message as an unknown command.

**Comment by sasha00123** [comment]
@DoopityWha Sorry, didn't notice your issue... 

The reason I added replies to the unprocessed message is that a whole lot of people were confused with the way bot works.

I believe I can add a command to the bot to disable such warnings.
