### ISSUE TITLE
ai_dungeon

### ISSUE THREAD

**Issue by Sqryz** [sasha00123/ai-dungeon-bot#3]
Привет. Попробовал запустить бота на CentOS, установил зависимости через poetry, но проблема в том, что он никак не видит/не устанавливает модуль ai_dungeon, да и наверное, вообще все модули, не мог бы помочь разобраться с этим?

**Comment by sasha00123** [comment]
@Sqryz Извиняюсь, последнее время очень занят. Получилось запустить?

Вообще, очень рекомендую использовать Docker - тогда не будет никаких проблем с совместимостью.
